### ISSUE TITLE
notify_multiple_devices isn't working

### ISSUE THREAD

**Issue by arvindnrbt** [LintelTechnologies/txFCM#5]
notify_multiple_devices throws an exception but notify_single_device doesn't but in both cases there is no notification. It seems to occur at twisted. Can someone tell me how to fix this? Here's the full stacktrace. 

`<txfcm.txfcm.TXFCMNotification object at 0x105fbd4a8>, 'message_title': 'Crosstalk', 'message_body': 'new post.', 'data_message': {}, 'registration_ids': 'some_id'}
Unhandled Error
Traceback (most recent call last):
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/base.py", line 428, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/base.py", line 441, in _continueFiring
    callable(*args, **kwargs)
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/base.py", line 1238, in _reallyStartRunning
    self._handleSignals()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 295, in _handleSignals
    _SignalReactorMixin._handleSignals(self)
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/base.py", line 1203, in _handleSignals
    signal.signal(signal.SIGINT, self.sigInt)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
builtins.ValueError: signal only works in main thread

[Failure instance: Traceback: <class 'AttributeError'>: 'Failure' object has no attribute 'code'
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:653:_runCallbacks
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:1117:_cbDeferred
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:459:callback
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:567:_startRunCallbacks
--- <exception caught here> ---
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:653:_runCallbacks
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/txfcm/txfcm.py:55:txparse_responses
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/txfcm/txfcm.py:69:parse
]
Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing
Traceback (most recent call last):
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/protocols/policies.py", line 125, in connectionLost
    self.wrappedProtocol.connectionLost(reason)
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/_newclient.py", line 964, in dispatcher
    return func(*args, **kwargs)
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/_newclient.py", line 1634, in _connectionLost_TRANSMITTING
    self._currentRequest.stopWriting()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/_newclient.py", line 865, in stopWriting
    _callAppFunction(self.bodyProducer.stopProducing)
--- <exception caught here> ---
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/_newclient.py", line 194, in _callAppFunction
    function()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/client.py", line 1086, in stopProducing
    self._task.stop()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/task.py", line 497, in stop
    self._checkFinish()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/task.py", line 507, in _checkFinish
    raise self._completionState
twisted.internet.task.TaskStopped: 

[Failure instance: Traceback: <class 'AttributeError'>: 'Failure' object has no attribute 'code'
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:653:_runCallbacks
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:1117:_cbDeferred
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:459:callback
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:567:_startRunCallbacks
--- <exception caught here> ---
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/defer.py:653:_runCallbacks
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/txfcm/txfcm.py:55:txparse_responses
/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/txfcm/txfcm.py:69:parse
]
Unexpected exception from twisted.web.client.FileBodyProducer.stopProducing
Traceback (most recent call last):
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/protocols/policies.py", line 125, in connectionLost
    self.wrappedProtocol.connectionLost(reason)
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/_newclient.py", line 964, in dispatcher
    return func(*args, **kwargs)
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/_newclient.py", line 1634, in _connectionLost_TRANSMITTING
    self._currentRequest.stopWriting()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/_newclient.py", line 865, in stopWriting
    _callAppFunction(self.bodyProducer.stopProducing)
--- <exception caught here> ---
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/_newclient.py", line 194, in _callAppFunction
    function()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/web/client.py", line 1086, in stopProducing
    self._task.stop()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/task.py", line 497, in stop
    self._checkFinish()
  File "/Users/arvindn/.virtualenvs/envaibc/lib/python3.6/site-packages/twisted/internet/task.py", line 507, in _checkFinish
    raise self._completionState
twisted.internet.task.TaskStopped: 
`

**Comment by rohitchormale** [comment]
Sorry got busy week, so not able to address it immediately. Can you please provide environment and steps to reproduce issue ?
